#!/bin/bash

for REP in {1..5}
do
    rm -r m5out
    # baseline three level
    build/X86/gem5.opt configs/learning_gem5/part1/three_level.py --l2_size='1MB' --l1d_size='128kB'

    cp -r m5out/ roba_out/three-level-baseline_rep$REP

    echo "Three level Baseline done!"

    rm -r m5out
    # random repl. policy
    build/X86/gem5.opt configs/learning_gem5/part1/three_level.py --l2_size='1MB' --l1d_size='128kB' --repl_policy="TrueRandomRP"

    cp -r m5out/ roba_out/three-level-random_rep$REP

    echo "Three level Random done"
done